export const abi = {
	version: "eosio::abi/1.2",
	types: [
		{ new_type_name: "B_vector_uint64_E", type: "uint64[]" },
		{
			new_type_name: "QUALI_ATOMIC_ADDRESS",
			type: "variant_name_uint32_uint64",
		},
		{ new_type_name: "address", type: "checksum160" },
		{ new_type_name: "content", type: "tuple_uint8_string" },
		{ new_type_name: "vaddress", type: "variant_address_name" },
	],
	structs: [
		{
			name: "Quali",
			base: "",
			fields: [
				{ name: "type", type: "uint8" },
				{ name: "address", type: "QUALI_ATOMIC_ADDRESS" },
				{ name: "data_filter", type: "QualiDataFilter?" },
			],
		},
		{
			name: "QualiDataFilter",
			base: "",
			fields: [
				{ name: "attr_id", type: "uint8" },
				{ name: "filter_type", type: "uint8" },
				{ name: "data", type: "bytes" },
			],
		},
		{
			name: "acctaskidx",
			base: "",
			fields: [
				{ name: "account_id", type: "uint32" },
				{ name: "campaign_id", type: "uint32" },
				{ name: "value", type: "uint32" },
			],
		},
		{
			name: "batch",
			base: "",
			fields: [
				{ name: "id", type: "uint32" },
				{ name: "campaign_id", type: "uint32" },
				{ name: "content", type: "content" },
				{ name: "balance", type: "extended_asset" },
				{ name: "repetitions", type: "uint32" },
				{ name: "num_tasks", type: "uint32" },
				{ name: "start_task_idx", type: "uint32" },
				{ name: "reward", type: "extended_asset" },
			],
		},
		{
			name: "campaign",
			base: "",
			fields: [
				{ name: "id", type: "uint32" },
				{ name: "reservations_done", type: "uint32" },
				{ name: "total_submissions", type: "uint32" },
				{ name: "total_tasks", type: "uint32" },
				{ name: "active_batch", type: "uint32" },
				{ name: "num_batches", type: "uint32" },
				{ name: "owner", type: "vaddress" },
				{ name: "paused", type: "bool" },
				{ name: "content", type: "content" },
				{ name: "max_task_time", type: "uint32" },
				{ name: "reward", type: "extended_asset" },
				{ name: "qualis", type: "Quali[]" },
			],
		},
		{ name: "clean", base: "", fields: [] },
		{
			name: "cleartasks",
			base: "",
			fields: [
				{ name: "batch_id", type: "uint32" },
				{ name: "campaign_id", type: "uint32" },
			],
		},
		{
			name: "editcampaign",
			base: "",
			fields: [
				{ name: "campaign_id", type: "uint32" },
				{ name: "owner", type: "vaddress" },
				{ name: "content", type: "content" },
				{ name: "paused", type: "bool" },
				{ name: "reward", type: "extended_asset" },
				{ name: "qualis", type: "Quali[]" },
				{ name: "payer", type: "name" },
			],
		},
		{
			name: "init",
			base: "",
			fields: [
				{ name: "vaccount_contract", type: "name" },
				{ name: "force_vaccount_id", type: "uint32" },
				{ name: "payout_delay_sec", type: "uint32" },
				{ name: "release_task_delay_sec", type: "uint32" },
				{ name: "fee_contract", type: "name" },
				{ name: "fee_percentage", type: "float32" },
			],
		},
		{
			name: "mkbatch",
			base: "",
			fields: [
				{ name: "id", type: "uint32" },
				{ name: "campaign_id", type: "uint32" },
				{ name: "content", type: "content" },
				{ name: "repetitions", type: "uint32" },
				{ name: "payer", type: "name" },
			],
		},
		{
			name: "mkcampaign",
			base: "",
			fields: [
				{ name: "owner", type: "vaddress" },
				{ name: "content", type: "content" },
				{ name: "max_task_time", type: "uint32" },
				{ name: "reward", type: "extended_asset" },
				{ name: "qualis", type: "Quali[]" },
				{ name: "payer", type: "name" },
			],
		},
		{
			name: "payment",
			base: "",
			fields: [
				{ name: "id", type: "uint64" },
				{ name: "account_id", type: "uint32" },
				{ name: "batch_id", type: "uint64" },
				{ name: "pending", type: "extended_asset" },
				{ name: "last_submission_time", type: "time_point_sec" },
			],
		},
		{
			name: "payout",
			base: "",
			fields: [{ name: "payment_id", type: "uint64" }],
		},
		{
			name: "publishbatch",
			base: "",
			fields: [
				{ name: "batch_id", type: "uint64" },
				{ name: "num_tasks", type: "uint32" },
			],
		},
		{
			name: "repsdone",
			base: "",
			fields: [
				{ name: "campaign_id", type: "uint32" },
				{ name: "task_idx", type: "uint32" },
				{ name: "value", type: "uint32" },
			],
		},
		{
			name: "reservation",
			base: "",
			fields: [
				{ name: "id", type: "uint64" },
				{ name: "task_idx", type: "uint32" },
				{ name: "account_id", type: "uint32?" },
				{ name: "batch_id", type: "uint64" },
				{ name: "reserved_on", type: "time_point_sec" },
				{ name: "campaign_id", type: "uint32" },
			],
		},
		{
			name: "reservetask",
			base: "",
			fields: [
				{ name: "campaign_id", type: "uint32" },
				{ name: "account_id", type: "uint32" },
				{ name: "quali_assets", type: "B_vector_uint64_E?" },
				{ name: "payer", type: "name" },
			],
		},
		{
			name: "rmbatch",
			base: "",
			fields: [
				{ name: "id", type: "uint32" },
				{ name: "campaign_id", type: "uint32" },
			],
		},
		{
			name: "rmcampaign",
			base: "",
			fields: [
				{ name: "campaign_id", type: "uint32" },
				{ name: "owner", type: "vaddress" },
			],
		},
		{
			name: "settings",
			base: "",
			fields: [
				{ name: "vaccount_contract", type: "name" },
				{ name: "force_vaccount_id", type: "uint32" },
				{ name: "payout_delay_sec", type: "uint32" },
				{ name: "release_task_delay_sec", type: "uint32" },
				{ name: "fee_contract", type: "name" },
				{ name: "fee_percentage", type: "float32" },
			],
		},
		{
			name: "submission",
			base: "",
			fields: [
				{ name: "id", type: "uint64" },
				{ name: "campaign_id", type: "uint32" },
				{ name: "task_idx", type: "uint32" },
				{ name: "account_id", type: "uint32?" },
				{ name: "content", type: "content?" },
				{ name: "batch_id", type: "uint64" },
				{ name: "data", type: "string?" },
				{ name: "paid", type: "bool" },
				{ name: "submitted_on", type: "time_point_sec" },
			],
		},
		{
			name: "submittask",
			base: "",
			fields: [
				{ name: "campaign_id", type: "uint32" },
				{ name: "task_idx", type: "uint32" },
				{ name: "data", type: "string" },
				{ name: "account_id", type: "uint32" },
				{ name: "payer", type: "name" },
			],
		},
		{
			name: "tuple_uint8_string",
			base: "",
			fields: [
				{ name: "field_0", type: "uint8" },
				{ name: "field_1", type: "string" },
			],
		},
	],
	actions: [
		{ name: "clean", type: "clean", ricardian_contract: "" },
		{ name: "cleartasks", type: "cleartasks", ricardian_contract: "" },
		{ name: "editcampaign", type: "editcampaign", ricardian_contract: "" },
		{ name: "init", type: "init", ricardian_contract: "" },
		{ name: "mkbatch", type: "mkbatch", ricardian_contract: "" },
		{ name: "mkcampaign", type: "mkcampaign", ricardian_contract: "" },
		{ name: "payout", type: "payout", ricardian_contract: "" },
		{ name: "publishbatch", type: "publishbatch", ricardian_contract: "" },
		{ name: "reservetask", type: "reservetask", ricardian_contract: "" },
		{ name: "rmbatch", type: "rmbatch", ricardian_contract: "" },
		{ name: "rmcampaign", type: "rmcampaign", ricardian_contract: "" },
		{ name: "submittask", type: "submittask", ricardian_contract: "" },
	],
	tables: [
		{
			name: "acctaskidx",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "acctaskidx",
		},
		{
			name: "batch",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "batch",
		},
		{
			name: "campaign",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "campaign",
		},
		{
			name: "payment",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "payment",
		},
		{
			name: "repsdone",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "repsdone",
		},
		{
			name: "reservation",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "reservation",
		},
		{
			name: "settings",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "settings",
		},
		{
			name: "submission",
			index_type: "i64",
			key_names: [],
			key_types: [],
			type: "submission",
		},
	],
	ricardian_clauses: [],
	error_messages: [],
	abi_extensions: [],
	variants: [
		{ name: "variant_address_name", types: ["address", "name"] },
		{ name: "variant_name_uint32_uint64", types: ["name", "uint32", "uint64"] },
	],
	action_results: [],
};
