const old_qualis = [
    { 'name': 'Force Qualifier: Image Classification', 'description': 'Basic Image Classification Proficiency. User demonstrates ability to sort and identify objects in images.', 'old_id': 327, 'new_id': null, 'new_name': null },
    { 'name': 'Basic English Proficiency', 'description': 'Basic English Proficiency. User demonstrates command and use of English language in a conversational manner. ', 'old_id': 459, 'new_id': null, 'new_name': null },
    { 'name': 'English (US) Proofreading', 'description': 'English US Proofreader. User has a high to expert level of English language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 193, 'new_id': null, 'new_name': null },
    { 'name': 'Chinese (Simplified) Translation/Proofreading', 'description': 'Chinese Language Translator/Proofreader. User has a high to expert level of Simplified Chinese language skills and a mastery of correct characters, radicals, proper structure, and an eye for detail. ', 'old_id': 195, 'new_id': null, 'new_name': null },
    { 'name': 'Indonesian Translation/Proofreading', 'description': 'Bahasa Indonesia Translator/Proofreader. User has a high to expert level of Bahasa Indonesia language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 268, 'new_id': null, 'new_name': null },
    { 'name': 'Arabic Translation/Proofreading', 'description': 'Arabic Translator/Proofreader. User has a high to expert level of Modern Standard Arabic skills and a master of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 270, 'new_id': null, 'new_name': null },
    { 'name': 'Spanish Translation/Proofreading', 'description': 'Spanish (EU) Translator/Proofreader. User has a high to expert level of European Spanish language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 189, 'new_id': null, 'new_name': null },
    { 'name': 'Portuguese (Brazilian) Translation/Proofreading', 'description': 'Portguese (Brazilian) Translator/Proofreader. User has a high to expert level of Brazilian Portuguese language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 192, 'new_id': null, 'new_name': null },
    { 'name': 'Italian Translation/Proofreading', 'description': 'Italian Translator/Proofreader. User has a high to expert level of Italian language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 271, 'new_id': null, 'new_name': null },
    { 'name': 'German Translation/Proofreading', 'description': 'German Translator/Proofreader. User has a high to expert level of German language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 320, 'new_id': null, 'new_name': null },
    { 'name': 'French Translation/Proofreading', 'description': 'French Translator/Proofreader. User has a high to expert level of French language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 269, 'new_id': null, 'new_name': null },
    { 'name': 'Polish Translation/Proofreading', 'description': 'Polish Translator/Proofreader. User has a high to expert level of Polish language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 267, 'new_id': null, 'new_name': null },
    { 'name': 'Dutch Translation/Proofreading', 'description': 'Dutch Translator/Proofreader. User has a high to expert level of Dutch language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 266, 'new_id': null, 'new_name': null },
    { 'name': 'Georgian Translation/Proofreading', 'description': 'Georgian Translator/Proofreader. User has a high to expert level of Georgian language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 254, 'new_id': null, 'new_name': null },
    { 'name': 'Russian Translation/Proofreading', 'description': 'Russian Translator/Proofreader. User has a high to expert level of Russian language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 194, 'new_id': null, 'new_name': null },
    { 'name': 'Turkish Translation/Proofreading', 'description': 'Turkish Translator/Proofreader. User has a high to expert level of Turkish language skills and a mastery of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Twitter Account (Self Select)', 'description': 'Twitter platform user. User has an active Twitter account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Discord Account (Self Select)', 'description': 'Discord platform user. User has an active Discord account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Facebook Account (Self Select)', 'description': 'Facebook platform user. User has an active Facebook account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'YouTube Account (Self Select)', 'description': 'YouTube platform user. User has an active YouTube account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Instagram Account (Self Select)', 'description': 'Instagram platform user. User has an active Instagram account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Telegram Account (Self Select)', 'description': 'Telegram platform user. User has an active Telegram account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'Reddit Account (Self Select)', 'description': 'Reddit platform user. User has an active Reddit account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'GitHub Account (Self Select)', 'description': 'GitHub platform user. User has an active GitHub account. ', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'ES Translation Validator', 'description': 'ES Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': null, 'new_id': null, 'new_name': null },
    { 'name': 'ZH Translation Validator', 'description': 'ZH Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 203, 'new_id': null, 'new_name': null },
    { 'name': 'PT Translation Validator', 'description': 'PT Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 205, 'new_id': null, 'new_name': null },
    { 'name': 'RU Translation Validator', 'description': 'RU Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 206, 'new_id': null, 'new_name': null },
    { 'name': 'ES Translation Master Validator', 'description': 'ES Translation Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 207, 'new_id': null, 'new_name': null },
    { 'name': 'ZH Translaiton Master Validator', 'description': 'ZH Translaiton Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 223, 'new_id': null, 'new_name': null },
    { 'name': 'RU Translation Master Validator', 'description': 'RU Translation Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 226, 'new_id': null, 'new_name': null },
    { 'name': 'PT Translation Master Validator', 'description': 'PT Translation Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 225, 'new_id': null, 'new_name': null },
    { 'name': 'NL Translation Validator', 'description': 'NL Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 224, 'new_id': null, 'new_name': null },
    { 'name': 'ID Translation Validator', 'description': 'ID Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 284, 'new_id': null, 'new_name': null },
    { 'name': 'PL Translation Validator', 'description': 'PL Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 285, 'new_id': null, 'new_name': null },
    { 'name': 'FR Translation Validator', 'description': 'FR Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 286, 'new_id': null, 'new_name': null },
    { 'name': 'IT Translation Validator', 'description': 'IT Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 287, 'new_id': null, 'new_name': null },
    { 'name': 'AR Translation Validator', 'description': 'AR Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 288, 'new_id': null, 'new_name': null },
    { 'name': 'Translation Master Validator', 'description': 'Translation Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 289, 'new_id': null, 'new_name': null },
    { 'name': 'Subtitle Master Validator', 'description': 'Subtitle Master Validator. User is expertly proficient in checking others` work and making corrections.', 'old_id': 290, 'new_id': null, 'new_name': null },
    { 'name': 'DE Translation Validator', 'description': 'DE Translation Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 292, 'new_id': null, 'new_name': null },
    { 'name': 'Closed Caption Test (Open Book)', 'description': 'Closed Caption Test (Open Book). User has familiarity in the captioning process and basic rules.', 'old_id': 326, 'new_id': null, 'new_name': null },
    { 'name': 'Effect FORCE Captioner', 'description': 'Effect FORCE Captioner. User has demonstrated they are proficient in closed caption creation, proofreading, and editing in accordance to closed captioning best practices.', 'old_id': 329, 'new_id': null, 'new_name': null },
    { 'name': 'KHMS Translator', 'description': 'KHMS Translator. User has completed requirements in order to complete tasks for KH. ', 'old_id': 418, 'new_id': null, 'new_name': null },
    { 'name': 'EN Native Captioner', 'description': 'EN Native Captioner. User has demonstrated a master of proficiency in creating captions in the English language from English (US) audio. ', 'old_id': 453, 'new_id': null, 'new_name': null },
    { 'name': 'Kastaar', 'description': 'Kastaar', 'old_id': 201, 'new_id': null, 'new_name': null },
    { 'name': 'Troubadour', 'description': 'Troubadour', 'old_id': 144, 'new_id': null, 'new_name': null },
    { 'name': 'Flemish Transcriber', 'description': 'Flemish Transcriber. User is proficient in transcribing and creating captions in Flemish. ', 'old_id': 117, 'new_id': null, 'new_name': null },
    { 'name': 'Dutch Caption Creator', 'description': 'Dutch Caption Creator. User has demonstrated a master of proficiency in creating captions in the Dutch language from Dutch audio. ', 'old_id': 209, 'new_id': null, 'new_name': null },
    { 'name': 'Special Sauce', 'description': 'Special Sauce. User demonstrated exceptional ability in completing tasks for KH', 'old_id': 305, 'new_id': null, 'new_name': null },
    { 'name': 'KHMS Translator', 'description': 'DUPLICATE LISTING, see above for TestnetQualifier #125', 'old_id': 418, 'new_id': null, 'new_name': null },
    { 'name': 'Pirate Translator/Proofreader', 'description': 'Pirate Translator/Proofreader', 'old_id': 461, 'new_id': null, 'new_name': null },
    { 'name': 'Storm Trooper 2021', 'description': 'Storm Trooper 2021', 'old_id': 473, 'new_id': null, 'new_name': null },
    { 'name': 'ar-EG Translator', 'description': 'Arabic Translator/Proofreader (Egyptian dialect). User has a high to expert level of Modern Standard Arabic skills in the Egyptian dialect, and a master of correct sentence structure, word choice, punctuation, and an eye for detail. ', 'old_id': 501, 'new_id': null, 'new_name': null },
    { 'name': 'ar-EG Validator', 'description': 'ar-EG Validator. User is proficient in checking others` work and validating for correctness.', 'old_id': 503, 'new_id': null, 'new_name': null },
]

const example_qualis = [

]
    
exports.old_qualis = {old_qualis, example_qualis};


/**
 *     { 'name': 'NL Translator Proofreader Blacklist ', 'description': 'NL Translator Proofreader Blacklist. User is removed from tasks requiring this qualification.  ' },
    { 'name': 'DE Translator Proofreader Blacklist', 'description': 'DE Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'ES Translator Proofreader Blacklist', 'description': 'ES Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'RU Translator Proofreader Blacklist', 'description': 'RU Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'PT Translator Proofreader Blacklist', 'description': 'PT Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'AR Translator Proofreader Blacklist', 'description': 'AR Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'ID Translator Proofreader Blacklist', 'description': 'ID Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'FR Translator Proofreader Blacklist', 'description': 'FR Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'IT Translator Proofreader Blacklist', 'description': 'IT Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'ZH Translator Proofreader Blacklist', 'description': 'ZH Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'PL Translator Proofreader Blacklist', 'description': 'PL Translator Proofreader Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'Validator Blacklist', 'description': 'Validator Blacklist. User is removed from tasks requiring this qualification. ' },
    { 'name': 'Block KH Tasks', 'description': 'Block KH Tasks. User is removed from tasks requiring this qualification. ' },
   bbb
 */