const old_qualis = [
    "Image classification",
    "Basic English Proficiency",
    "English (US) Proofreading",
    "Chinese (Simplified) Translation/Proofreading",
    "Indonesian Translation/Proofreading",
    "Arabic Translation/Proofreading",
    "Spanish Translation/Proofreading",
    "Portuguese (Brazilian) Translation/Proofreading",
    "Italian Translation/Proofreading",
    "German Translation/Proofreading",
    "French Translation/Proofreading",
    "Polish Translation/Proofreading",
    "Dutch Translation/Proofreading",
    "Georgian Translation/Proofreading",
    "Russian Translation/Proofreading",
    "Turkish Translation/Proofreading",
    "Twitter Account (Self Select)",
    "Discord Account (Self Select)",
    "Facebook Account (Self Select)",
    "YouTube Account (Self Select)",
    "Instagram Account (Self Select)",
    "Telegram Account (Self Select)",
    "Reddit Account (Self Select)",
    "GitHub Account (Self Select)",
    "ES Translation Validator",
    "ZH Translation Validator",
    "PT Translation Validator",
    "RU Translation Validator",
    "ES Translation Master Validator",
    "ZH Translaiton Master Validator",
    "RU Translation Master Validator",
    "PT Translation Master Validator",
    "NL Translation Validator",
    "ID Translation Validator",
    "PL Translation Validator",
    "FR Translation Validator",
    "IT Translation Validator",
    "AR Translation Validator",
    "Translation Master Validator",
    "Subtitle Master Validator",
    "DE Translation Validator",
    "Closed Caption Test (Open Book)",
    "Effect FORCE Captioner",
    "NL Translator Proofreader Blacklist ",
    "DE Translator Proofreader Blacklist",
    "ES Translator Proofreader Blacklist",
    "RU Translator Proofreader Blacklist",
    "PT Translator Proofreader Blacklist",
    "AR Translator Proofreader Blacklist",
    "ID Translator Proofreader Blacklist",
    "FR Translator Proofreader Blacklist",
    "IT Translator Proofreader Blacklist",
    "ZH Translator Proofreader Blacklist",
    "PL Translator Proofreader Blacklist",
    "Validator Blacklist",
    "KHMS Translator",
    "Block KH Tasks",
    "EN Native Captioner",
    "Kastaar",
    "Troubadour",
    "Pirate Translator/Proofreader",
    "Flemish Transcriber",
    "Dutch Caption Creator",
    "Special Sauce",
    "KHMS Translator",
    "Storm Trooper 2021",
    "ar-EG Translator",
    "ar-EG Validator",
];

exports.old_qualis = old_qualis;
