name: Deploy on gh-pages

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'  # Replace with the desired Node.js version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      
      # builds the sdk
      - run: bun run build
      
      # builds the docs
      - run: cd docs && bun install --frozen-lockfile && bun run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
