name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Setup Bun

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun format && bun lint

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: format"
          commit_user_name: "github-actions[bot]"

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Setup Bun

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun build
